export const ADD_PERSON_SAGA = 'ADD_PERSON_SAGA';
export const ADD_PERSON_REDUCER = 'ADD_PERSON_REDUCER';

export const EDIT_PERSON_SAGA = 'EDIT_PERSON_SAGA';
export const EDIT_PERSON_REDUCER = 'EDIT_PERSON_REDUCER';

export const DELETE_PERSON_SAGA = 'DELETE_PERSON_SAGA';
export const DELETE_PERSON_REDUCER = 'DELETE_PERSON_REDUCER';

export const GET_PERSONS_SAGA = 'GET_PERSONS_SAGA';
export const GET_PERSONS_REDUCER = 'GET_PERSONS_REDUCER';

export const DO_SOMETHING = 'DO_SOMETHING';

export const UI_START_LOADING = 'UI_START_LOADING';
export const UI_STOP_LOADING = 'UI_STOP_LOADING';